// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9ASEVShd2Ki5Mw6uB3xyvS048kgtsKs',
    appId: '1:10843972329:web:93eda19852c6accfe04678',
    messagingSenderId: '10843972329',
    projectId: 'mintlesignuplogin',
    authDomain: 'mintlesignuplogin.firebaseapp.com',
    storageBucket: 'mintlesignuplogin.appspot.com',
    measurementId: 'G-FZC7W3ZJB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMteavmUnmSmGvDt0A-Qa7vCOiaKqE7o4',
    appId: '1:10843972329:android:a9cbcf8ab723386ee04678',
    messagingSenderId: '10843972329',
    projectId: 'mintlesignuplogin',
    storageBucket: 'mintlesignuplogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVigxaWUpruBYbzS5VExY_8L32BuISU8',
    appId: '1:10843972329:ios:6ed12e2bb8e11497e04678',
    messagingSenderId: '10843972329',
    projectId: 'mintlesignuplogin',
    storageBucket: 'mintlesignuplogin.appspot.com',
    iosBundleId: 'com.example.mintleLoginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWVigxaWUpruBYbzS5VExY_8L32BuISU8',
    appId: '1:10843972329:ios:ea809adc86f57096e04678',
    messagingSenderId: '10843972329',
    projectId: 'mintlesignuplogin',
    storageBucket: 'mintlesignuplogin.appspot.com',
    iosBundleId: 'com.example.mintleLoginSignup.RunnerTests',
  );
}
